# -*- coding: utf-8 -*-
"""featureimportance_decisiontree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CkfIHnL3dALwbq8ES4Y5Mt4_sM5G_sDh
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

#load the Iris Dataset
iris=load_iris()
X=iris.data
y=iris.target

#split The dataset Into Training And Testiong sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#create A decion Tree classifier
clf=DecisionTreeClassifier(random_state=42)

#fit the Classifier To the traing Data
clf.fit(X_train,y_train)

# Get  Feature importances
feature_importances=clf.feature_importances_

#print feature importnaces
for feature, importance in zip(iris.feature_names, feature_importances):
    print(f"{feature}: {importance}")

"""## #Random Forest Classifier




"""

rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)
rf_clf.fit(X_train, y_train)
feature_importances = rf_clf.feature_importances_

et_clf = ExtraTreesClassifier(n_estimators=100, random_state=42)
et_clf.fit(X_train, y_train)
feature_importances = et_clf.feature_importances_

